<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/"
                  xmlns:tns="http://com/tfkfan/webservices/categoryservice"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  targetNamespace="http://com/tfkfan/webservices/categoryservice">
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://com/tfkfan/webservices/categoryservice" schemaLocation="../xsd/category.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="CreateCategoryRequest">
        <wsdl:part element="tns:CreateCategoryRequest" name="createCategoryRequest" />
    </wsdl:message>
    <wsdl:message name="CreateCategoryResponse">
        <wsdl:part element="tns:CreateCategoryResponse" name="createCategoryResponse" />
    </wsdl:message>
    <wsdl:portType name="CategoryService">
        <wsdl:operation name="CreateCategory">
            <wsdl:input message="tns:CreateCategoryRequest" />
            <wsdl:output message="tns:CreateCategoryResponse" />
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="CategoryServiceSoapBinding" type="tns:CategoryService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="CreateCategory">
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="CategoryService">
        <wsdl:port binding="tns:CategoryServiceSoapBinding" name="CategoryServicePort">
            <soap:address
                location="http://localhost:8080/categoryservice" />
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
